---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    kubernetes.io/metadata.name: appdev-openshift-gitops
  name: appdev-openshift-gitops
spec:
  finalizers:
  - kubernetes
