apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  annotations:
  name: argocd
spec:
  dex:
    openShiftOAuth: true
  rbac:
    defaultPolicy: 'role:admin'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  server:
    route:
      enabled: true
    service:
      type: ""
  tls:
   ca: {}